[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["./src/**", "./supabase/**"] # include relevant source folders
  external_node_modules = ["@google/generative-ai", "@supabase/supabase-js", "node-fetch"]

  [functions."*"]
    node_module_format = "esm"

[build.environment]
  NODE_VERSION = "18"
