[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[functions]
  node_bundler = "esbuild"
  included_files = ["./src/**", "./supabase/**"] # IMPORTANT: Include relevant root-level folders
  external_node_modules = ["@google/generative-ai", "@supabase/supabase-js"] # Add any other large npm modules your functions use

  [functions."*"] # Apply ESM format to all functions
    node_module_format = "esm"