[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"   # <-- Add this line to specify the functions directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
