[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "./src/**",
    "./supabase/**"
  ]
  external_node_modules = [
    "@google/generative-ai",
    "@supabase/supabase-js",
    "node-fetch"
  ]

  [functions."*"]
    node_module_format = "esm"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"